default_agent: cicerone
agents:
  cicerone:
    name: cicerone
    entrypoint: /Users/davidvictoria/Desktop/ciceron/app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_13
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/davidvictoria/Desktop/ciceron
    aws:
      execution_role: arn:aws:iam::131578276461:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-f7aeb2424d
      execution_role_auto_create: false
      account: '131578276461'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-131578276461-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: cicerone-szUAIIHGxh
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:131578276461:runtime/cicerone-szUAIIHGxh
      agent_session_id: bc7e0489-ad79-4fe3-be82-50c125e83db3
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
